#!/bin/bash

#create vm use virt-install



#Determine parameters 
if [ $# -lt 5 ] 
    then 
        echo -e "Warning:The script must have five parameters."
        echo "#########################################################################"
        echo "Usage: sh $0 vmname vcpunum memory disk ipaddress" 
        echo  -e "Example: sh $0 icpdbs 8 16 500 10.2.7.12"
        echo "#########################################################################"
        exit 1
    else
        echo "Will create ${1} vm"    
   fi

WORKDIR="/var/lib/libvirt/images/"
VMNAME=$1
VCPU=$2
MEM=$(expr $3 \* 1024)
DSIZE=$4
IPADDR=$5

#Determine if the virtual machine exists
echo "Determine if the virtual machine exists"
virsh list --all|awk  '{print$2}'|sed '1,2d'|grep -E "^${VMNAME}"
if [ $? -eq 0 ];then
    echo "The ${VMNAME} already exists"
    exit 1
fi
cd ${WORKDIR}
if [ -d  "${VMNAME}" ];then
    echo "The vm ${VMNAME} dir already exists"
else
    mkdir ${VMNAME}
    echo "The vm ${VMNAME} created successful"
fi  

cd ${VMNAME}
#disk resize
cp /home/ubuntu/centos72x86_64_cloud-init.qcow2 system.qcow2
cp /home/ubuntu/cloud.cfg cloud.cfg
#
if [ "${DSIZE}" -le 40 ];then

    echo "The vm disk less 40GB do not resize"
else
    resizenum=$(expr $DSIZE - 40)G
    qemu-img resize system.qcow2 +${resizenum}
fi
#create vm ipaddress files
cat >ifcfg-eth0 <<EOF
# Generated by parse-kickstart
DEVICE="eth0"
IPV6INIT="no"
BOOTPROTO="static"
ONBOOT="yes"
IPADDR=${IPADDR}
NETMASK=255.255.252.0
GATEWAY=10.2.7.254
EOF
#create hostname
echo "${VMNAME}" >hostname
#create vm
   
virt-install --name ${VMNAME}.inspurcloudtest.com --disk path=/var/lib/libvirt/images/${VMNAME}/system.qcow2,bus=virtio,cache=none --network bridge:br_mgm,model=virtio --ram ${MEM}  --vcpus ${VCPU} --accelerate --boot hd --vnc --vnclisten 0.0.0.0 --noreboot --autostart --import 
#virt-copy-in -d ${VMNAME}.inspurcloudtest.com ${WORKDIR}cloud.cfg /etc/cloud/
sleep 5
virsh start ${VMNAME}.inspurcloudtest.com
sleep 180
virsh destroy ${VMNAME}.inspurcloudtest.com
sleep 3
echo "Beginning set vm ipaddress"

virt-copy-in -d ${VMNAME}.inspurcloudtest.com ifcfg-eth0 /etc/sysconfig/network-scripts/
virt-copy-in -d ${VMNAME}.inspurcloudtest.com hostname /etc/
virt-copy-in -d ${VMNAME}.inspurcloudtest.com cloud.cfg /etc/cloud/

virsh start ${VMNAME}.inspurcloudtest.com
#virsh list
virsh list